
spring:
  datasource:
    password: xcontrol
    url: jdbc:mysql://10.9.8.7/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true